<?php
/**
 * @file
 * This is a simple module that prints out the cached wordpress sidebar
 * content.
 */

/**
 * Implementation of hook_help().
 */
function wpnewscol_help($path, $arg) {
  switch ($path) {
    case 'wpnewscol':
      return '<p>'. t('A simple module to include the cached file containing Wordpress news in a sidebar.') .'</p>';
  }
}

/**
 * Implementation of hook_block().
 */
function wpnewscol_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == "list") {
    $block = array();
    $block[0]["info"] = t('Wordpress Latest News Sidebar');
    return $block;
  }
  elseif ($op == 'view') {
    $block['subject'] = 'Latest News';
    $block['content'] = file_get_contents('/var/www/theme/includes/extracol.html');
    return $block;
  }
}
