<?php
/**
 * @file
 * This is a simple module that includes the problem of the week in a sidebar.
 */

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function potw_block_info() {
  $blocks[0] = array(
    'info' => t('Problem of the Week'),
  );
  return $blocks;
}


/**
 * Implementation of hook_block().
 */
function potw_block_view($delta = 0) {
  $block['subject'] = 'Problem of the Week';
  $block['content'] = file_get_contents('/var/www/usgo.org/problems/current_go_problem.inc');
  return $block;
}
