<?php

global $markdown_abbr_abbrs;
$markdown_abbr_abbrs = <<<ENDOFABBR
*[AGA]: American Go Association
*[AGF]: American Go Foundation
*[POTW]: Problem of the Week
*[KGS]: KGS Go Server
*[IGS]: Internet Go Server
*[IGF]: International Go Federation
ENDOFABBR;
/**
 * Implements hook_filter_info().
 *
 */
function markdown_abbr_filter_info() {
    $filters['markdown_abbr'] = array(
            'title' => t('Markdown Predefined Acronymns/abbreviations'),
            'description' => t('Predefines acronyms for Markdown.'),
            'process callback'  => '_markdown_abbr_process',
            'tips callback' => '_markdown_abbr_tips',
            );
    return $filters;
}

/**
 * Filter tips callback
 *
 */
function _markdown_abbr_tips($filter, $format, $long = FALSE) {
    global $markdown_abbr_abbrs;
    $ret = t('Predefines acronyms for use in Markdown');
    if (!$long) {
        $ret .= ":\n" . $markdown_abbr_abbrs;
    }
    return $ret;
}

function _markdown_abbr_process($text, $filter) {
    global $markdown_abbr_abbrs;
    return $markdown_abbr_abbrs . "\n\n\n" . $text;
}

