<?php
/**
 * @file
 * This is a simple module that prints out the cached wordpress sidebar
 * content.
 */

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function wpnewscol_block_info() {
  $blocks[0] = array(
    'info' => t('Wordpress Latest News Sidebar'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block().
 */
function wpnewscol_block_view($delta = 0) {
  $block['subject'] = 'Latest News';
  $block['content'] = file_get_contents('/var/www/usgo.org/theme/includes/extracol.html');
  return $block;
}
