<?php
// $Id: mean_menus.module,v 1.75 2010/10/09 17:19:51 add1sun Exp $

/**
 * @file
 *  Module to enable CSS dropdown and flyout menus.
 *
 * Maintainer: Addison Berry (add1sun)
 * Originally written by Jake Gordon (jakeg)
 *
 * Heavily customized and bastardized by Joshua Simmons
 */

/**
 * Implementation of hook_help().
 */
function mean_menus_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/modules#description':
      $output .= t('Make custom CSS menus for site and admin menus.');
      break;
    case 'admin/settings/mean_menus':
      $output .= t('<p>This is a simple module that enables the site to have custom CSS menus for site and admin navigation.</p><p>Remember to activate and configure the menu blocks in !link</p>', array('!link' => l('admin/build/block', 'admin/build/block')));
      break;
  }
  return $output;
}

/**
 * Implementation of hook_form_alter().
function mean_menus_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'system_theme_settings':

      // This is a global setting, so only insert the field
      // on the global settings page.
      if (arg(4) && arg(4) != 'global') {
        return;
      }

      // Have to add a custom submit handler since this form doesn't use
      // the standard system submit handler.
      $form['#submit'][] = 'mean_menus_system_theme_settings_submit';

      // Add global theme setting for a custom CSS file.
      $form['mean_menus_custom_css'] = array(
        '#type' => 'textfield',
        '#title' => t('Path to custom Mean menus CSS file'),
        '#description' => t('To override the default Mean menus CSS layout, enter the path to your custom CSS file.  It should be a relative path from the root of your Drupal install (e.g. sites/all/themes/example/mymenu.css).'),
        '#default_value' => variable_get('mean_menus_custom_css', ''),
        // Field appears below submit buttons without this -- yucky.
        '#weight' => 0,
      );
      break;
  }
}

/**
 * Records the Mean menu custom CSS file per theme.
function mean_menus_system_theme_settings_submit($form, &$form_state) {
  variable_set('mean_menus_custom_css', $form_state['values']['mean_menus_custom_css']);
}
*/

/**
 * Implementation of hook_menu().
 */
function mean_menus_menu() {
  $items['admin/settings/mean_menus'] = array(
    'title' => 'Mean menus',
    'description' => 'Configure Mean menus.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mean_menus_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Settings form as implemented by hook_menu
 */
function mean_menus_admin_settings() {
  $form['mean_menus_number'] = array(
    '#type' => 'textfield',
    '#description' => t('The total number of independent Mean menus blocks you want. Enter a number between 0 and 99. If you set this to 0, you will have no blocks created but you can still use the Mean menus theme functions directly in your theme.'),
    '#default_value' => variable_get('mean_menus_number', '2'),
    '#size' => 2,
  );
/*  $form['mean_menus_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use JavaScript'),
    '#description' => t('This will add Superfish Jquery to Mean menus. This is required for Mean menus to work properly in Internet Explorer.'),
    '#default_value' => variable_get('mean_menus_js', 1),
  );
  $form['mean_menus_sf_options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced: Superfish options'),
    '#description' => t('You can change the default Superfish options by filling out the desired values here. These only take effect if the Use JavaScript box above is checked.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['mean_menus_sf_options']['mean_menus_sf_delay'] = array(
    '#type' => 'textfield',
    '#title' => t('Mouse delay'),
    '#description' => t('The delay in milliseconds that the mouse can remain outside a submenu without it closing.'),
    '#default_value' => variable_get('mean_menus_sf_delay', 800),
    '#size' => 5,
  );
  $form['mean_menus_sf_options']['mean_menus_sf_speed'] = array(
    '#type' => 'select',
    '#title' => t('Animation speed'),
    '#multiple' => FALSE,
    '#description' => t('Speed of the menu open/close animation.'),
    '#options' => array('slow' => t('slow'), 'normal' => t('normal'), 'fast' => t('fast')),
    '#default_value' => variable_get('mean_menus_sf_speed', 1),
     );
*/
  // Custom validation to make sure the user is entering numbers.
  $form['#validate'][] = 'mean_menus_settings_validate';

  return system_settings_form($form);
}

/**
 * Custom validation for the settings form.
 */
function mean_menus_settings_validate($form, &$form_state) {
  $number = $form_state['values']['mean_menus_number'];
  // Check to make sure it is a number and that is a maximum of 2 digits.
  if (!is_numeric($number) || strlen($number) > 2) {
      form_set_error('mean_menus_number', t('You must enter a number from 0 to 99.'));
  }
}

/**
 * Implementation of hook_init().
 *
 * We are adding the JavaScript and CSS here rather than theme_mean_menu
 * because when block caching is enabled none of it would get fired
 * and the menus are unstyled.
 */
function mean_menus_init() {
/*  // Add Superfish JavaScript, if enabled.
  if (variable_get('mean_menus_js', 1) == 1) {
    // The script, from http://users.tpg.com.au/j_birch/plugins/superfish.
    drupal_add_js(drupal_get_path('module', 'mean_menus') .'/superfish/js/superfish.js');
    // Add the Superfish options variables.
    drupal_add_js(array(
      'mean_menus_options' => array(
        'delay' => variable_get('mean_menus_sf_delay', 800),
        'speed' => variable_get('mean_menus_sf_speed', 1),
        )),'setting');
    // Add the bgIframe plugin.
    drupal_add_js(drupal_get_path('module', 'mean_menus') .'/superfish/js/jquery.bgiframe.min.js');
    // Add the HoverIntent plugin.
    drupal_add_js(drupal_get_path('module', 'mean_menus') .'/superfish/js/jquery.hoverIntent.minified.js');
    // The Mean menus implementation.
    drupal_add_js(drupal_get_path('module', 'mean_menus') .'/mean_menus.js');
  }
	
  // Add main CSS functionality.
  drupal_add_css(drupal_get_path('module', 'mean_menus') .'/mean_menus.css');
  // Add custom CSS layout if specified.
  if ($custom = variable_get('mean_menus_custom_css', '')) {
    drupal_add_css($custom);
  }
  // Fall back to default layout.
  else {
    drupal_add_css(drupal_get_path('module', 'mean_menus') .'/mean_menus_default.css');
  }
*/
}

/**
 * Implementation of hook_block().
 */
function mean_menus_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;

  switch ($op) {
    case 'list':
      for ($i = 1; $i <= variable_get('mean_menus_number', '2'); $i++) {
        $blocks[$i]['info'] = variable_get('mean_menus_name_'. $i, 'Mean menu '. $i) .' (Mean menu)';
        // We have too many things changing per user, per page to cache.
        $blocks[$i]['cache'] = BLOCK_NO_CACHE;
      }
      return $blocks;
    break;

    case 'configure':
      $form['mean_menus_name_'. $delta] = array(
        '#type' => 'textfield',
        '#title' => t('Menu Name'),
        '#default_value' => variable_get('mean_menus_name_'. $delta, 'Mean menu '. $delta),
      );
      $form['mean_menus_menu_'. $delta] = array(
        '#type' => 'select',
        '#title' => t('Menu Parent'),
        '#description' => t('The menu parent from which to show a Mean menu.'),
        '#default_value' => variable_get('mean_menus_menu_'. $delta, 'navigation:0'),
        '#options' => menu_parent_options(menu_get_menus(), 0),
      );
      $form['mean_menus_depth_'. $delta] = array(
       '#type' => 'select',
       '#title' => t('Menu Depth'),
       '#description' => t('The depth of the menu, i.e. the number of child levels starting with the parent selected above. Leave set to -1 to display all children and use 0 to display no children.'),
       '#default_value' => variable_get('mean_menus_depth_'. $delta, -1),
       '#options' => drupal_map_assoc(range(-1, 5))
      );
/*      $form['mean_menus_type_'. $delta] = array(
        '#type' => 'select',
        '#title' => t('Menu Style'),
        '#description' => t('right: menu items are listed on top of each other and expand to the right') .'<br />'. t('left: menu items are listed on top of each other and expand to the left') .'<br />'. t('down: menu items are listed side by side and expand down'),
        '#default_value' => variable_get('mean_menus_type_'. $delta, 'right'),
        '#options' => drupal_map_assoc(array('right', 'left', 'down')),
      );
 */
      $form['mean_menus_classes_'. $delta] = array(
        '#type' => 'textfield',
        '#title' => t('Menu Classes'),
        '#description' => t('CSS classes to add to the menu when displayed'),
        '#default_value' => variable_get('mean_menus_classes_'. $delta, ''),
      );
      $form['mean_menus_id_'. $delta] = array(
        '#type' => 'textfield',
        '#title' => t('Menu Id'),
        '#description' => t('CSS id to add to the menu when displayed'),
        '#default_value' => variable_get('mean_menus_id_'. $delta, 'mean-menu-'. $delta),
      );
      return $form;
    break;

    case 'save':
      variable_set('mean_menus_name_'. $delta, $edit['mean_menus_name_'. $delta]);
      variable_set('mean_menus_menu_'. $delta, $edit['mean_menus_menu_'. $delta]);
      variable_set('mean_menus_depth_'. $delta, $edit['mean_menus_depth_'. $delta]);
      variable_set('mean_menus_classes_'. $delta, $edit['mean_menus_classes_'. $delta]);
      variable_set('mean_menus_id_'. $delta, $edit['mean_menus_id_'. $delta]);      
//      variable_set('mean_menus_type_'. $delta, $edit['mean_menus_type_'. $delta]);
    break;

    case 'view':
      // Build the Mean menu for the block.
      list($menu_name, $mlid) = explode(':', variable_get('mean_menus_menu_'. $delta, 'navigation:0'));
//      $direction = variable_get('mean_menus_type_'. $delta, 'right');
      $class = variable_get('mean_menus_classes_'. $delta, '');
      $id = variable_get('mean_menus_id_'. $delta, '');      
      $depth = variable_get('mean_menus_depth_'. $delta, '-1');
      if ($output = theme('mean_menus', $menu_name, $mlid, $class, $id, $depth)) {
        $block['content'] = $output['content'];
/*        if (variable_get('mean_menus_type_'. $delta, 'right') == 'down') {
          $class = 'mean-menu-hide-title';
        }
        else {
          $class = 'mean-menu-show-title';
        }
*/
        // If we're building the navigation block
        // use the same block title logic as menu module.
        if ($output['subject'] == t('Navigation') && $user->uid) {
          $subject = $user->name;
        }
        else {
          $subject = $output['subject'];
        }
        $block['subject'] = '<span class="menu-title">'. check_plain($subject) .'</span>';
      }
      else {
        $block['content'] = FALSE;
      }
      return $block;
    break;
  }
}

/**
 * Implementation of hook_theme().
 */
function mean_menus_theme() {
  return array(
    'mean_menus_tree' => array(
      'arguments' => array('menu_name' => NULL, 'mlid' => NULL, 'depth' => -1, 'menu' => NULL),
    ),
    'mean_menus_build' => array(
      'arguments' => array('menu' => NULL,  'depth' => -1, 'trail' => NULL),
    ),
    'mean_menus' => array(
      'arguments' => array('id' => NULL, 'menu_name' => NULL, 'mlid' => NULL, 'depth' => -1, 'menu' => NULL),
    ),
    'mean_menus_primary_links' => array(
      'arguments' => array('depth' => -1, 'menu' => NULL),
    ),
    'mean_menus_secondary_links' => array(
      'arguments' => array('depth' => -1, 'menu' => NULL),
    ),
/*
    // Deprecated theme functions that will be removed in 7.x.
    'mean_menu_tree' => array(
      'arguments' => array('menu_name' => NULL, 'mlid' => NULL, 'depth' => -1, 'menu' => NULL),
    ),
    'mean_menu_build' => array(
      'arguments' => array('menu' => NULL,  'depth' => -1, 'trail' => NULL),
    ),
    'mean_menu' => array(
      'arguments' => array('id' => NULL, 'menu_name' => NULL, 'mlid' => NULL, 'direction' => 'right', 'depth' => -1, 'menu' => NULL),
    ),
    'mean_menu_primary_links' => array(
      'arguments' => array('direction' => 'down', 'depth' => -1, 'menu' => NULL),
  ),
*/
  );
}

/**
 * Builds the active trail from the page's menu data.
 *
 * @param $page_menu
 *   The menu data for a page.
 * @return
 *   An array of parent menu item ids.
 */
function mean_menus_build_page_trail($page_menu) {
  $trail = array();
  foreach ($page_menu as $item) {
    if ($item['link']['in_active_trail']) {
      $trail[] = $item['link']['mlid'];
    }
    if ($item['below']) {
      $trail = array_merge($trail, mean_menus_build_page_trail($item['below']));
    }
  }
  return $trail;
}

/**
 * Builds the final Mean menu.
 *
 * @param $menu_name
 *   The top-level menu name that contains the menu to use (e.g. navigation
 *   or primary-links) for Drupal menus. For custom $menus this is just the
 *   name for menu display.
 * @param $mlid
 *   The menu ID from which to start building the items, i.e. the parent
 *   of the displayed menu.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming -- it should have
 *   the same structure as that returned by menu_tree_all_data().
 * @return
 *   An HTML string of properly nested Mean menu lists.
 */
function theme_mean_menus_tree($menu_name, $mlid = NULL, $depth = -1, $menu = NULL) {
  // Load the full menu array.
  $menu = isset($menu) ? $menu : menu_tree_all_data($menu_name);

  if (isset($menu)) {
    $page_menu = menu_tree_page_data($menu_name);
    $trail = mean_menus_build_page_trail($page_menu);
    unset($page_menu);
  }

  // Allow i18n module to translate strings where available.
  if (module_exists('i18nmenu')) {
    i18nmenu_localize_tree($menu);
  }

  // For custom $menus and menus built all the way from the top-level we
  // don't need to "create" the specific sub-menu and we need to get the title
  // from the $menu_name since there is no "parent item" array.

  // Create the specific menu if we have a mlid.
  if (!empty($mlid)) {
    // Load the parent menu item.
    $item = menu_link_load($mlid);
    $title = check_plain($item['title']);
    // The depth for our parent item.
    $parent_depth = $item['depth'];

    // Narrow down the full menu to the specific sub-tree we need.
    for ($p = 1; $p < 10; $p++) {
      if ($sub_mlid = $item["p$p"]) {
        $subitem = menu_link_load($sub_mlid);
        // Menu sets these ghetto-ass keys in _menu_tree_check_access().
        $menu = $menu[(50000 + $subitem['weight']) .' '. $subitem['title'] .' '. $subitem['mlid']]['below'];
      }
    }
  }
  // Otherwise just set a title and move on.
  else {
    // Get the title from the DB since we don't have it in the $menu.
    $result = db_result(db_query("SELECT title FROM {menu_custom} WHERE menu_name = '%s'", $menu_name));
    $title = check_plain($result);
  }

  $output['content'] = '';
  $output['subject'] = $title;

  if ($menu) {
    // Set the total menu depth counting from this parent if we need it.
    $depth =  ($depth > 0) ? ($parent_depth + $depth) : $depth;
    $output['content'] .= theme('mean_menus_build', $menu, $depth, $trail);
  }

  return $output;
}

/**
 * Helper function that builds the nested lists of a Mean menu.
 *
 * @param $menu
 *   Menu array from which to build the nested lists.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $trail
 *   An array of parent menu items.
 */
function theme_mean_menus_build($menu, $depth = -1, $trail = NULL) {
  $output = '';
  // Prepare to count the links so we can mark first, last, odd and even.
  $index = 0;
  $count = 0;
  foreach ($menu as $menu_count) {
    if ($menu_count['link']['hidden'] == 0) {
      $count++;
    }
  }
  // Get to building the menu.
  foreach ($menu as $menu_item) {
    $mlid = $menu_item['link']['mlid'];
    // Check to see if it is a visible menu item.
    if (!isset($menu_item['link']['hidden']) || $menu_item['link']['hidden'] == 0) {
      // Check our count and build first, last, odd/even classes.
      $index++;
      $first_class = $index == 1 ? ' first ' : '';
      $oddeven_class = $index % 2 == 0 ? ' even ' : ' odd ';
      $last_class = $index == $count ? ' last ' : '';
      // Build class name based on menu path
      // e.g. to give each menu item individual style.
      // Strip funny symbols.
      $clean_path = str_replace(array('http://', 'www', '<', '>', '&', '=', '?', ':', '.'), '', $menu_item['link']['href']);
      // Convert slashes to dashes.
      $clean_path = str_replace('/', '-', $clean_path);
      $class = 'menu-path-'. $clean_path;
      if ($trail && in_array($mlid, $trail)) {
        $class .= ' active-trail';
      }
      // If it has children build a mean little tree under it.
      if ((!empty($menu_item['link']['has_children'])) && (!empty($menu_item['below'])) && $depth != 0) {
        // Keep passing children into the function 'til we get them all.
        $children = theme('mean_menus_build', $menu_item['below'], $depth, $trail);
        // Set the class to parent only of children are displayed.
        $is_parent = ($children && ($menu_item['link']['depth'] <= $depth || $depth == -1));
        $output .= '<li class="menu-' . $mlid . ' ' . $class . $first_class . $oddeven_class . $last_class .'">';
        if (!$is_parent)
        {
            $output .= theme('menu_item_link', $menu_item['link']);
        }
        else
        {
            $output .= '<span class="opener">'. $menu_item['link']['link_title'] .'</span>';
        }
        // Check our depth parameters.
        if ($menu_item['link']['depth'] <= $depth || $depth == -1) {
          // Build the child UL only if children are displayed for the user.
          if ($children) {
            $output .= '<ul>';
            $output .= $children;
            $output .= "</ul>\n";
          }
        }
        $output .= "</li>\n";
      }
      else {
        $output .= '<li class="menu-' . $mlid . ' ' . $class . $first_class . $oddeven_class . $last_class .'">'. theme('menu_item_link', $menu_item['link']) .'</li>'."\n";
      }
    }
  }
  return $output;
}

/**
 * Theme function to allow any menu tree to be themed as a Mean menu.
 *
 * @param $id
 *   The Mean menu ID.
 * @param $menu_name
 *   The top parent menu name from which to build the full menu.
 * @param $mlid
 *   The menu ID from which to build the displayed menu.
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'right'.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *  by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of Mean menu links.
 */
function theme_mean_menus($menu_name, $mlid, $class = '', $id = '', $depth = -1, $menu = NULL) {
  $output = array();
  $class_temp = '';
  $id_temp = '';
  if (!empty($class))
  {
      $class_temp = "class=\"$class\"";
  }
  if (!empty($id))
  {
      $id_temp = "id=\"$id\"";
  }
  if ($menu_tree = theme('mean_menus_tree', $menu_name, $mlid, $depth, $menu)) {
    if ($menu_tree['content']) {
      $output['content'] = "<ul $class_temp $id_temp>". $menu_tree['content'] .'</ul>'."\n";
      $output['subject'] = $menu_tree['subject'];
    }
  }
  return $output;
}

/**
 * Theme primary links as Mean menus.
 *
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'down'.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *   by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of Mean menu primary links.
 */
function theme_mean_menus_primary_links($class = '', $id = '', $depth = -1, $menu = NULL) {
  $menu_name = variable_get('menu_primary_links_source', 'primary-links');
  $output = theme('mean_menus', $menu_name, 0, $class, $id, $depth, $menu);
  return $output['content'];
}

/**
 * Theme secondary links as mean menus.
 *
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'down'.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *   by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of mean menu secondary links.
 */
function theme_mean_menus_secondary_links($class = '', $id = '', $depth = -1, $menu = NULL) {
  $menu_name = variable_get('menu_secondary_links_source', 'secondary-links');
  $output = theme('mean_menus', $menu_name, 0, $class, $id, $depth, $menu);
  return $output['content'];
}
