<?php
/**
 * @file
 * A filter which changes float: right and float: left styles into the
 * css classes I'd like.
 */

/**
 * Implementation of hook_filter_tips().
 *
 */
function imagealign_filter_tips($delta, $format, $long = FALSE) {
  switch ($delta) {
    case 0:
      if ($long) {
        return t('Replace float:right and float:left produced by WYSIWYG editor with required css classes.');
      }
      break;
  }
}

/**
 * Implementation of hook_filter().
 *
 * The bulk of filtering work is done here.
 */
function imagealign_filter($op, $delta = 0, $format = -1, $text = '') {
  // The "list" operation provides the module an opportunity to declare both how
  // many filters it defines and a human-readable name for each filter. Note that
  // the returned name should be passed through t() for translation.
  if ($op == 'list') {
    return array(0 => t('Floats to CSS classes'));
  }

  switch ($delta) {
    case 0:
      switch ($op) {
        case 'description':
          return t('Replace float:right and float:left produced by WYSIWYG editor with required css classes.');

        case 'prepare': // not needed, return same text
          return $text;

        case 'process':
          return preg_replace('/style\s*=\s*"float:\s*(left|right);?"/i',
                              'class="align$1"', $text);
      }
      break;
  }
}
?>
