<?php
/**
 * @file
 * This is a simple module that prints out our visa advert
 */

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function visaad_block_info() {
  $blocks[0] = array(
    'info' => t('Visa Advert'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block().
 */
function visaad_block_view($delta = 0) {
  $block['subject'] = 'AGA Capital One Visa';
  $block['content'] = <<<EOC
<a href="http://www.cardlabconnect.com/AffinityPortal/visitorAction.do?affinityName=AGA"><img src="/files/aga_visa_card.png" alt="AGA Capital One Visa card" class="graphic" width="145px" height="92px" /></a>
<p>Get the <a href="http://www.cardlabconnect.com/AffinityPortal/visitorAction.do?affinityName=AGA"><abbr title="American Go Association">AGA</abbr> Visa card</a> from Capital One and support go every time you make a purchase. No annual fee!</p>
EOC;
  return $block;
}
