<?php
/**
 * @file
 * This is a simple module that prints out our custom google site search box.
 */

/**
 * Implementation of hook_help().
 */
function oursitesearch_help($path, $arg) {
  switch ($path) {
    case 'oursitesearch':
      return '<p>'. t('A simple module to show our custom google site search box.') .'</p>';
  }
}

/**
 * Implementation of hook_block().
 */
function oursitesearch_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == "list") {
    $block = array();
    $block[0]["info"] = t('Our Custom Site Search Box');
    return $block;
  }
  elseif ($op == 'view') {
    $block['subject'] = 'Site Search';
    $block['content'] = '<form class="search" id="sitesearch" action="http://www.google.com/search"><fieldset><legend>Site Search</legend><input type="text" class="searchbox" id="q" name="q" maxlength="255" value="" /><input type="hidden" name="sitesearch" value="usgo.org" /><input type="submit" class="searchbutton" id="searchbutton" value="Search" /></fieldset></form>';
    return $block;
  }
}
